# Generated by Django 3.0.8 on 2020-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='restaurant_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
